spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dress_renting
    username: postgres
    password: nermin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: memmedlinermin205@gmail.com
    password: cxwyxtidljofkyph
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
    default-encoding: UTF-8
server:
  port: 8085

cloudinary:
  cloud:
    name: thenermin
  api:
    key: 955757652539184
    secret: iKNxSLdUW3Tqyn7ZQk56UzmdNiY

jwt:
  secret: "Q1dbkjbkbkhkvgjtycycyrHb2lVbldmZ1pDb1ZyT0p0T1l0cERLVEpLQkRWRU1NTEdMQU1VTVVNRVJUTlNUVVJHRVJHQjA0Q0xBVE1FVFRFUjEyMzQ1Njc4OTAx"
  jwtExpirationMs: 600000
  refreshExpirationMs: 86400000